version: '2'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    command: mongod

  app:
    build: .
    container_name: app
    depends_on:
      - mongodb
    links:
      - mongodb
